/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pClock = (uint32_t *) 0x40023830;
	uint32_t *pMode = (uint32_t *) 0x40020000;
	uint32_t *pOutput_data = (uint32_t *) 0x40020014;

	//1. enable the clock for GPIOA in AHB1ENR
	// no la vi tri bit thu
	*pClock |= 0x01;

	//2. configure GPIOA mode as output
	//a, clear 11 and 10 pin to 0
	*pMode &= ~(1<<10);
	*pMode &= ~(1<<11);
	//b, set 10 to 1
	*pMode |= (1<<10);
	//3. Set PA5 pin to output data register to make i/o pin 5 -> HIGH = set 5 to 1

	// turn on and off between 0.56s
	// t = (so vong lap + so cycle/vong) + CPU (Hz)
	while(1){
	*pOutput_data |= (1<<5); // turn on led
	// this loop excute 10.000 times
	for(uint32_t i = 0; i < 600000; i++);

	*pOutput_data &= ~(1<<5); // turn off led

	for(uint32_t i = 0; i < 600000; i++);
	// khi dung vong lap nay, cpu se bi chiem dung bo nho
	// khong lam duoc gi khac (nhan tin hieu, xu ly)
	// cach nay thuc su khong toi uu
	}
}













